/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\github\\fore-end\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-2acb9eef",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2acb9eef").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-591d2534",
    path: "/blog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-591d2534").then(next)
    },
  },
  {
    name: "v-5a42164c",
    path: "/countup.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a42164c").then(next)
    },
  },
  {
    name: "v-c836ff42",
    path: "/css/a-css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c836ff42").then(next)
    },
  },
  {
    name: "v-18da951f",
    path: "/css/c-css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18da951f").then(next)
    },
  },
  {
    name: "v-f7a14942",
    path: "/interview/interview.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f7a14942").then(next)
    },
  },
  {
    name: "v-e7e86dce",
    path: "/http/http.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e7e86dce").then(next)
    },
  },
  {
    name: "v-72e8fb59",
    path: "/javascript/javascript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72e8fb59").then(next)
    },
  },
  {
    name: "v-a8ed3d18",
    path: "/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a8ed3d18").then(next)
    },
  },
  {
    path: "/css/index.html",
    redirect: "/css/"
  },
  {
    name: "v-4b40ea82",
    path: "/css/b-css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b40ea82").then(next)
    },
  },
  {
    name: "v-4614494e",
    path: "/typescript/typescript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4614494e").then(next)
    },
  },
  {
    name: "v-15bbb519",
    path: "/vue3/vue3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15bbb519").then(next)
    },
  },
  {
    name: "v-95138dce",
    path: "/vue2/vue2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-95138dce").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]