/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "每日笔记",
  "description": "前端每日面试题",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "周帅帅"
      }
    ],
    [
      "meta",
      {
        "name": "Keywords",
        "content": "前端面试题介绍"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/img/hero.png",
        "heroText": "Fore End",
        "tagline": "前端面试题总结",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-2acb9eef",
      "path": "/",
      "lastUpdated": "1 天",
      "lastUpdatedTimestamp": 1681312264000
    },
    {
      "title": "css主页",
      "frontmatter": {},
      "regularPath": "/css/",
      "relativePath": "css/README.md",
      "key": "v-a8ed3d18",
      "path": "/css/",
      "headers": [
        {
          "level": 2,
          "title": "css主页",
          "slug": "css主页"
        }
      ],
      "lastUpdated": "1 天",
      "lastUpdatedTimestamp": 1681312264000
    },
    {
      "title": "aa",
      "frontmatter": {},
      "regularPath": "/css/a-css.html",
      "relativePath": "css/a-css.md",
      "key": "v-c836ff42",
      "path": "/css/a-css.html",
      "lastUpdated": "1 天",
      "lastUpdatedTimestamp": 1681312264000
    },
    {
      "title": "cc",
      "frontmatter": {},
      "regularPath": "/css/c-css.html",
      "relativePath": "css/c-css.md",
      "key": "v-18da951f",
      "path": "/css/c-css.html",
      "lastUpdated": "1 天",
      "lastUpdatedTimestamp": 1681312264000
    },
    {
      "title": "bb",
      "frontmatter": {},
      "regularPath": "/css/b-css.html",
      "relativePath": "css/b-css.md",
      "key": "v-4b40ea82",
      "path": "/css/b-css.html",
      "lastUpdated": "1 天",
      "lastUpdatedTimestamp": 1681312264000
    },
    {
      "frontmatter": {},
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-b9ba5728",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "navbar: true\ntitle: css",
          "slug": "navbar-truetitle-css"
        },
        {
          "level": 2,
          "title": "关于我1",
          "slug": "关于我1"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题"
        },
        {
          "level": 3,
          "title": "二级标题",
          "slug": "二级标题"
        }
      ],
      "lastUpdated": "1 天",
      "lastUpdatedTimestamp": 1681312264000
    }
  ],
  "themeConfig": {
    "lastUpdated": "更新时间",
    "logo": "/assets/img/hero.png",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/about"
      },
      {
        "text": "Languages",
        "items": [
          {
            "text": "Group1",
            "items": [
              {
                "text": "Home",
                "link": "/"
              },
              {
                "text": "Home",
                "link": "/"
              }
            ]
          },
          {
            "text": "Group2",
            "items": [
              {
                "text": "Home",
                "link": "/"
              },
              {
                "text": "Home",
                "link": "/"
              }
            ]
          },
          {
            "text": "Group2",
            "items": [
              {
                "text": "Home",
                "link": "/"
              },
              {
                "text": "Home",
                "link": "/"
              }
            ]
          }
        ]
      },
      {
        "text": "External",
        "link": "https://google.com"
      }
    ],
    "sidebar": [
      "/",
      "/about",
      {
        "title": "css标题",
        "path": "/css/",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/css/a-css",
          "/css/b-css",
          "/css/c-css"
        ]
      }
    ]
  }
}