/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "周帅帅",
  "description": "前端每日面试题",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/study.ico"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "周帅帅"
      }
    ],
    [
      "meta",
      {
        "name": "Keywords",
        "content": "前端面试题介绍"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "href": "/apple-touch-icon.png"
      }
    ],
    [
      "link",
      {
        "rel": "manifest",
        "href": "/manifest.json"
      }
    ],
    [
      "link",
      {
        "rel": "stylesheet",
        "href": "https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.css"
      }
    ],
    [
      "link",
      {
        "rel": "stylesheet",
        "href": "/css/index.css"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#ffffff"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/img/hero.png",
        "heroText": "A Personal Blog",
        "tagline": "周帅帅的个人博客",
        "actionText": "开始 →",
        "actionLink": "./interview/interview",
        "features": [
          {
            "title": "初衷",
            "details": "记录一路走来学习的前端面试知识，方便之后复习与查看。"
          },
          {
            "title": "送自己的话",
            "details": "一个人可以走的很快，一群人才能走的更远，种一棵树最好的时间是十年前，其次就是现在"
          },
          {
            "title": "未来",
            "details": "起于此，但不止于此"
          }
        ],
        "footer": "Copyright © 2023 Zhou shuaishuai"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-2acb9eef",
      "path": "/",
      "lastUpdated": "1 年",
      "lastUpdatedTimestamp": 1683473401000,
      "createdTime": 1681225768000
    },
    {
      "frontmatter": {},
      "regularPath": "/blog.html",
      "relativePath": "blog.md",
      "key": "v-591d2534",
      "path": "/blog.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我1",
          "slug": "关于我1"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题"
        },
        {
          "level": 3,
          "title": "二级标题",
          "slug": "二级标题"
        }
      ],
      "lastUpdated": "1 年",
      "lastUpdatedTimestamp": 1683429218000,
      "createdTime": 1681743842000
    },
    {
      "title": "aa",
      "frontmatter": {},
      "regularPath": "/css/a-css.html",
      "relativePath": "css/a-css.md",
      "key": "v-c836ff42",
      "path": "/css/a-css.html",
      "lastUpdated": "1 年",
      "lastUpdatedTimestamp": 1681312264000,
      "createdTime": 1681312264000
    },
    {
      "title": "bb",
      "frontmatter": {},
      "regularPath": "/css/b-css.html",
      "relativePath": "css/b-css.md",
      "key": "v-4b40ea82",
      "path": "/css/b-css.html",
      "lastUpdated": "1 年",
      "lastUpdatedTimestamp": 1681312264000,
      "createdTime": 1681312264000
    },
    {
      "title": "css主页",
      "frontmatter": {},
      "regularPath": "/css/",
      "relativePath": "css/README.md",
      "key": "v-a8ed3d18",
      "path": "/css/",
      "headers": [
        {
          "level": 2,
          "title": "css主页",
          "slug": "css主页"
        }
      ],
      "lastUpdated": "1 年",
      "lastUpdatedTimestamp": 1681312264000,
      "createdTime": 1681312264000
    },
    {
      "title": "cc",
      "frontmatter": {},
      "regularPath": "/css/c-css.html",
      "relativePath": "css/c-css.md",
      "key": "v-18da951f",
      "path": "/css/c-css.html",
      "lastUpdated": "1 年",
      "lastUpdatedTimestamp": 1681312264000,
      "createdTime": 1681312264000
    },
    {
      "title": "Http",
      "frontmatter": {
        "navbar": true,
        "sidebar": "auto",
        "title": "Http"
      },
      "regularPath": "/http/http.html",
      "relativePath": "http/http.md",
      "key": "v-e7e86dce",
      "path": "/http/http.html",
      "headers": [
        {
          "level": 2,
          "title": "http2",
          "slug": "http2"
        }
      ],
      "lastUpdated": "1 年",
      "lastUpdatedTimestamp": 1683392497000,
      "createdTime": 1683392497000
    },
    {
      "title": "CountUp 第三方组件",
      "frontmatter": {
        "title": "CountUp 第三方组件"
      },
      "regularPath": "/countup.html",
      "relativePath": "countup.md",
      "key": "v-5a42164c",
      "path": "/countup.html",
      "lastUpdated": "1 年",
      "lastUpdatedTimestamp": 1683429218000,
      "createdTime": 1681654356000
    },
    {
      "title": "前端面试集合",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/interview/interview.html",
      "relativePath": "interview/interview.md",
      "key": "v-f7a14942",
      "path": "/interview/interview.html",
      "headers": [
        {
          "level": 2,
          "title": "HTML面试题",
          "slug": "html面试题"
        },
        {
          "level": 3,
          "title": "HTML语义化标签",
          "slug": "html语义化标签"
        },
        {
          "level": 3,
          "title": "HTML标签块级元素和内联元素",
          "slug": "html标签块级元素和内联元素"
        },
        {
          "level": 2,
          "title": "CSS面试题",
          "slug": "css面试题"
        },
        {
          "level": 3,
          "title": "盒模型的宽度计算",
          "slug": "盒模型的宽度计算"
        },
        {
          "level": 3,
          "title": "margin纵向重叠的问题",
          "slug": "margin纵向重叠的问题"
        },
        {
          "level": 3,
          "title": "margin负值的问题",
          "slug": "margin负值的问题"
        },
        {
          "level": 3,
          "title": "BFC理解和应用",
          "slug": "bfc理解和应用"
        },
        {
          "level": 3,
          "title": "float布局和clearfix",
          "slug": "float布局和clearfix"
        },
        {
          "level": 3,
          "title": "圣杯布局和双飞翼布局",
          "slug": "圣杯布局和双飞翼布局"
        },
        {
          "level": 2,
          "title": "JavaScript基础知识题",
          "slug": "javascript基础知识题"
        },
        {
          "level": 3,
          "title": "值类型和引用类型",
          "slug": "值类型和引用类型"
        },
        {
          "level": 3,
          "title": "typeof 运算符",
          "slug": "typeof-运算符"
        },
        {
          "level": 3,
          "title": "深拷贝111",
          "slug": "深拷贝111"
        },
        {
          "level": 2,
          "title": "ES6",
          "slug": "es6"
        },
        {
          "level": 3,
          "title": "var和let和const",
          "slug": "var和let和const"
        }
      ],
      "lastUpdated": "1 天",
      "lastUpdatedTimestamp": 1713190986000,
      "createdTime": 1683392497000
    },
    {
      "title": "javascript1",
      "frontmatter": {
        "navbar": true,
        "sidebar": "auto",
        "title": "javascript1"
      },
      "regularPath": "/javascript/javascript.html",
      "relativePath": "javascript/javascript.md",
      "key": "v-72e8fb59",
      "path": "/javascript/javascript.html",
      "headers": [
        {
          "level": 2,
          "title": "javascript2",
          "slug": "javascript2"
        },
        {
          "level": 2,
          "title": "sidebar: auto",
          "slug": "sidebar-auto"
        },
        {
          "level": 2,
          "title": "VSCode和文件说明",
          "slug": "vscode和文件说明"
        }
      ],
      "lastUpdated": "1 年",
      "lastUpdatedTimestamp": 1683392497000,
      "createdTime": 1683392497000
    },
    {
      "title": "Typescript",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/typescript/typescript.html",
      "relativePath": "typescript/typescript.md",
      "key": "v-4614494e",
      "path": "/typescript/typescript.html",
      "headers": [
        {
          "level": 2,
          "title": "VScode 和 文件说明",
          "slug": "vscode-和-文件说明"
        },
        {
          "level": 3,
          "title": "点击图片右键复制图片地址，在浏览器的新标签页打开，放大后就能看清楚图片内容",
          "slug": "点击图片右键复制图片地址-在浏览器的新标签页打开-放大后就能看清楚图片内容"
        },
        {
          "level": 3,
          "title": "图片中对应的文字说明",
          "slug": "图片中对应的文字说明"
        }
      ],
      "lastUpdated": "1 年",
      "lastUpdatedTimestamp": 1683392497000,
      "createdTime": 1683392497000
    },
    {
      "title": "vue3",
      "frontmatter": {
        "sidebar": "auto",
        "title": "vue3"
      },
      "regularPath": "/vue2/vue2.html",
      "relativePath": "vue2/vue2.md",
      "key": "v-95138dce",
      "path": "/vue2/vue2.html",
      "lastUpdated": "1 年",
      "lastUpdatedTimestamp": 1683430609000,
      "createdTime": 1683392497000
    },
    {
      "title": "vue3",
      "frontmatter": {
        "sidebar": "auto",
        "title": "vue3"
      },
      "regularPath": "/vue3/vue3.html",
      "relativePath": "vue3/vue3.md",
      "key": "v-15bbb519",
      "path": "/vue3/vue3.html",
      "lastUpdated": "1 年",
      "lastUpdatedTimestamp": 1683392497000,
      "createdTime": 1683392497000
    }
  ],
  "themeConfig": {
    "lastUpdated": "更新时间",
    "nav": [
      {
        "text": "前端面试集合",
        "link": "../../interview/interview"
      },
      {
        "text": "Typescript",
        "link": "../../typescript/typescript.md"
      },
      {
        "text": "Vue源码分析",
        "items": [
          {
            "text": "Vue2源码分析",
            "link": "../../vue2/vue2.md"
          },
          {
            "text": "Vue3源码分析",
            "link": "../../vue3/vue3.md"
          }
        ]
      },
      {
        "text": "Github",
        "link": "https://github.com/zssLove/fore-end"
      }
    ],
    "search": true,
    "searchMaxSuggestions": 10
  }
}